### ISSUE TITLE
Criação da página sobre o projeto

### ISSUE THREAD

**Issue by MariaFake** [LitzaGusmao/github-master#3]
Vocês poderiam criar uma página sobre o projeto? Obrigada!

**Comment by LitzaGusmao** [comment]
A página está em produção.

**Comment by MariaFake** [comment]
Obrigada! Estou aguardando.

**Comment by MariaFake** [comment]
Você pode, por favor, colocar seu telefone no site?

**Comment by MariaFake** [comment]
Você pode, por favor, colocar seu telefone no site @LitzaGusmao ?
